unit XENOME.OBS.Types;

interface

{$MINENUMSIZE 4}

const
  LIBOBS_API_MAJOR_VER = 30;
  LIBOBS_API_MINOR_VER = 0;
  LIBOBS_API_PATCH_VER = 2;
  LIBOBS_API_VER       = (LIBOBS_API_MAJOR_VER SHL 24) OR (LIBOBS_API_MINOR_VER SHL 16) OR LIBOBS_API_PATCH_VER;

  LOG_ERROR   = 100;
  LOG_WARNING = 200;
  LOG_INFO    = 300;
  LOG_DEBUG   = 400;

  MAX_CONVERT_BUFFERS = 3;
  MAX_CACHE_SIZE = 16;
  MAX_AV_PLANES = 8;

  MAX_AUDIO_MIXES = 6;
  MAX_AUDIO_MIXES_SOURCE = 1;

  MAX_AUDIO_CHANNELS = 8;
  AUDIO_OUTPUT_FRAMES = 1024;

  TOTAL_AUDIO_SIZE = MAX_AUDIO_MIXES * MAX_AUDIO_CHANNELS * AUDIO_OUTPUT_FRAMES * SizeOf(Single);

  AUDIO_OUTPUT_SUCCESS = 0;
  AUDIO_OUTPUT_INVALIDPARAM = -1;
  AUDIO_OUTPUT_FAIL = -2;

  OBS_SOURCE_VIDEO = 1 SHL 0;
  OBS_SOURCE_AUDIO = 1 SHL 1;
  OBS_SOURCE_ASYNC = 1 SHL 2;
  OBS_SOURCE_ASYNC_VIDEO = OBS_SOURCE_ASYNC OR OBS_SOURCE_VIDEO;
  OBS_SOURCE_CUSTOM_DRAW = 1 SHL 3;
  OBS_SOURCE_INTERACTION = 1 SHL 5;
  OBS_SOURCE_COMPOSITE = 1 SHL 6;
  OBS_SOURCE_DO_NOT_DUPLICATE = 1 SHL 7;
  OBS_SOURCE_DEPRECATED = 1 SHL 8;
  OBS_SOURCE_DO_NOT_SELF_MONITOR = 1 SHL 9;
  OBS_SOURCE_CAP_DISABLED = 1 SHL 10;
  OBS_SOURCE_CAP_OBSOLETE = OBS_SOURCE_CAP_DISABLED;
  OBS_SOURCE_MONITOR_BY_DEFAULT = 1 SHL 11;
  OBS_SOURCE_SUBMIX = 1 SHL 12;
  OBS_SOURCE_CONTROLLABLE_MEDIA = 1 SHL 13;
  OBS_SOURCE_CEA_708 = 1 SHL 14;
  OBS_SOURCE_SRGB = 1 SHL 15;
  OBS_SOURCE_CAP_DONT_SHOW_PROPERTIES = 1 SHL 16;

type
  TOBSEncoderType = (
    OBS_ENCODER_AUDIO,
    OBS_ENCODER_VIDEO
  );

  TOBSVideoFormat = (
    VIDEO_FORMAT_NONE,
    VIDEO_FORMAT_I420,
    VIDEO_FORMAT_NV12,
    VIDEO_FORMAT_YVYU,
    VIDEO_FORMAT_YUY2,
    VIDEO_FORMAT_UYVY,
    VIDEO_FORMAT_RGBA,
    VIDEO_FORMAT_BGRA,
    VIDEO_FORMAT_BGRX,
    VIDEO_FORMAT_Y800,
    VIDEO_FORMAT_I444,
    VIDEO_FORMAT_BGR3,
    VIDEO_FORMAT_I422,
    VIDEO_FORMAT_I40A,
    VIDEO_FORMAT_I42A,
    VIDEO_FORMAT_YUVA,
    VIDEO_FORMAT_AYUV,
    VIDEO_FORMAT_I010,
    VIDEO_FORMAT_P010,
    VIDEO_FORMAT_I210,
    VIDEO_FORMAT_I412,
    VIDEO_FORMAT_YA2L,
    VIDEO_FORMAT_P216,
    VIDEO_FORMAT_P416,
    VIDEO_FORMAT_V210,
    VIDEO_FORMAT_R10L
  );

  TOBSVideoTRC = (
    VIDEO_TRC_DEFAULT,
    VIDEO_TRC_SRGB,
    VIDEO_TRC_PQ,
    VIDEO_TRC_HLG
  );

  TOBSVideoColorspace = (
    VIDEO_CS_DEFAULT,
    VIDEO_CS_601,
    VIDEO_CS_709,
    VIDEO_CS_SRGB,
    VIDEO_CS_2100_PQ,
    VIDEO_CS_2100_HLG
  );

  TOBSVideoRangeType = (
    VIDEO_RANGE_DEFAULT,
    VIDEO_RANGE_PARTIAL,
    VIDEO_RANGE_FULL
  );

  TOBSVideoscaleType = (
    VIDEO_SCALE_DEFAULT,
    VIDEO_SCALE_POINT,
    VIDEO_SCALE_FAST_BILINEAR,
    VIDEO_SCALE_BILINEAR,
    VIDEO_SCALE_BICUBIC
  );

  TOBSFrontendEvent = (
    OBS_FRONTEND_EVENT_STREAMING_STARTING,
    OBS_FRONTEND_EVENT_STREAMING_STARTED,
    OBS_FRONTEND_EVENT_STREAMING_STOPPING,
    OBS_FRONTEND_EVENT_STREAMING_STOPPED,
    OBS_FRONTEND_EVENT_RECORDING_STARTING,
    OBS_FRONTEND_EVENT_RECORDING_STARTED,
    OBS_FRONTEND_EVENT_RECORDING_STOPPING,
    OBS_FRONTEND_EVENT_RECORDING_STOPPED,
    OBS_FRONTEND_EVENT_SCENE_CHANGED,
    OBS_FRONTEND_EVENT_SCENE_LIST_CHANGED,
    OBS_FRONTEND_EVENT_TRANSITION_CHANGED,
    OBS_FRONTEND_EVENT_TRANSITION_STOPPED,
    OBS_FRONTEND_EVENT_TRANSITION_LIST_CHANGED,
    OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGED,
    OBS_FRONTEND_EVENT_SCENE_COLLECTION_LIST_CHANGED,
    OBS_FRONTEND_EVENT_PROFILE_CHANGED,
    OBS_FRONTEND_EVENT_PROFILE_LIST_CHANGED,
    OBS_FRONTEND_EVENT_EXIT,

    OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTING,
    OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTED,
    OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPING,
    OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPED,

    OBS_FRONTEND_EVENT_STUDIO_MODE_ENABLED,
    OBS_FRONTEND_EVENT_STUDIO_MODE_DISABLED,
    OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED,

    OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP,
    OBS_FRONTEND_EVENT_FINISHED_LOADING,

    OBS_FRONTEND_EVENT_RECORDING_PAUSED,
    OBS_FRONTEND_EVENT_RECORDING_UNPAUSED,

    OBS_FRONTEND_EVENT_TRANSITION_DURATION_CHANGED,
    OBS_FRONTEND_EVENT_REPLAY_BUFFER_SAVED,

    OBS_FRONTEND_EVENT_VIRTUALCAM_STARTED,
    OBS_FRONTEND_EVENT_VIRTUALCAM_STOPPED,

    OBS_FRONTEND_EVENT_TBAR_VALUE_CHANGED,
    OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGING,
    OBS_FRONTEND_EVENT_PROFILE_CHANGING,
    OBS_FRONTEND_EVENT_SCRIPTING_SHUTDOWN,
    OBS_FRONTEND_EVENT_PROFILE_RENAMED,
    OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED,
    OBS_FRONTEND_EVENT_THEME_CHANGED,
    OBS_FRONTEND_EVENT_SCREENSHOT_TAKEN
  );

  TOBSAudioFormat = (
    AUDIO_FORMAT_UNKNOWN,

    AUDIO_FORMAT_U8BIT,
    AUDIO_FORMAT_16BIT,
    AUDIO_FORMAT_32BIT,
    AUDIO_FORMAT_FLOAT,

    AUDIO_FORMAT_U8BIT_PLANAR,
    AUDIO_FORMAT_16BIT_PLANAR,
    AUDIO_FORMAT_32BIT_PLANAR,
    AUDIO_FORMAT_FLOAT_PLANAR
  );

  TOBSSpeakerLayout = (
    SPEAKERS_UNKNOWN,
    SPEAKERS_MONO,
    SPEAKERS_STEREO,
    SPEAKERS_2POINT1,
    SPEAKERS_4POINT0,
    SPEAKERS_4POINT1,
    SPEAKERS_5POINT1,
    SPEAKERS_7POINT1 = 8
  );

  TOBSSourceType = (
    OBS_SOURCE_TYPE_INPUT,
    OBS_SOURCE_TYPE_FILTER,
    OBS_SOURCE_TYPE_TRANSITION,
    OBS_SOURCE_TYPE_SCENE
  );

  TOBSBalanceType = (
    OBS_BALANCE_TYPE_SINE_LAW,
    OBS_BALANCE_TYPE_SQUARE_LAW,
    OBS_BALANCE_TYPE_LINEAR
  );

  TOBSIconType = (
    OBS_ICON_TYPE_UNKNOWN,
    OBS_ICON_TYPE_IMAGE,
    OBS_ICON_TYPE_COLOR,
    OBS_ICON_TYPE_SLIDESHOW,
    OBS_ICON_TYPE_AUDIO_INPUT,
    OBS_ICON_TYPE_AUDIO_OUTPUT,
    OBS_ICON_TYPE_DESKTOP_CAPTURE,
    OBS_ICON_TYPE_WINDOW_CAPTURE,
    OBS_ICON_TYPE_GAME_CAPTURE,
    OBS_ICON_TYPE_CAMERA,
    OBS_ICON_TYPE_TEXT,
    OBS_ICON_TYPE_MEDIA,
    OBS_ICON_TYPE_BROWSER,
    OBS_ICON_TYPE_CUSTOM,
    OBS_ICON_TYPE_PROCESS_AUDIO_OUTPUT
  );

  TOBSMediaState = (
    OBS_MEDIA_STATE_NONE,
    OBS_MEDIA_STATE_PLAYING,
    OBS_MEDIA_STATE_OPENING,
    OBS_MEDIA_STATE_BUFFERING,
    OBS_MEDIA_STATE_PAUSED,
    OBS_MEDIA_STATE_STOPPED,
    OBS_MEDIA_STATE_ENDED,
    OBS_MEDIA_STATE_ERROR
  );

  TOBSDataType = (
    OBS_DATA_NULL,
    OBS_DATA_STRING,
    OBS_DATA_NUMBER,
    OBS_DATA_BOOLEAN,
    OBS_DATA_OBJECT,
    OBS_DATA_ARRAY
  );

  TOBSDataNumberType = (
    OBS_DATA_NUM_INVALID,
    OBS_DATA_NUM_INT,
    OBS_DATA_NUM_DOUBLE
  );

  TOBSDArray = record
    Data: Pointer;
    Num: UInt64;
    Capacity: UInt64;
  end;

implementation

end.
