unit XENOME.OBS.Types;

interface

{$MINENUMSIZE 4}

const
  LIBOBS_API_MAJOR_VER = 30;
  LIBOBS_API_MINOR_VER = 0;
  LIBOBS_API_PATCH_VER = 2;
  LIBOBS_API_VER       = (LIBOBS_API_MAJOR_VER SHL 24) OR (LIBOBS_API_MINOR_VER SHL 16) OR LIBOBS_API_PATCH_VER;

  LOG_ERROR   = 100;
  LOG_WARNING = 200;
  LOG_INFO    = 300;
  LOG_DEBUG   = 400;

  MAX_CONVERT_BUFFERS = 3;
  MAX_CACHE_SIZE = 16;
  MAX_AV_PLANES = 8;

  MAX_AUDIO_MIXES = 6;
  MAX_AUDIO_MIXES_SOURCE = 1;

  MAX_AUDIO_CHANNELS = 8;
  AUDIO_OUTPUT_FRAMES = 1024;

  TOTAL_AUDIO_SIZE = MAX_AUDIO_MIXES * MAX_AUDIO_CHANNELS * AUDIO_OUTPUT_FRAMES * SizeOf(Single);

  AUDIO_OUTPUT_SUCCESS = 0;
  AUDIO_OUTPUT_INVALIDPARAM = -1;
  AUDIO_OUTPUT_FAIL = -2;

  OBS_SOURCE_VIDEO = 1 SHL 0;
  OBS_SOURCE_AUDIO = 1 SHL 1;
  OBS_SOURCE_ASYNC = 1 SHL 2;
  OBS_SOURCE_ASYNC_VIDEO = OBS_SOURCE_ASYNC OR OBS_SOURCE_VIDEO;
  OBS_SOURCE_CUSTOM_DRAW = 1 SHL 3;
  OBS_SOURCE_INTERACTION = 1 SHL 5;
  OBS_SOURCE_COMPOSITE = 1 SHL 6;
  OBS_SOURCE_DO_NOT_DUPLICATE = 1 SHL 7;
  OBS_SOURCE_DEPRECATED = 1 SHL 8;
  OBS_SOURCE_DO_NOT_SELF_MONITOR = 1 SHL 9;
  OBS_SOURCE_CAP_DISABLED = 1 SHL 10;
  OBS_SOURCE_CAP_OBSOLETE = OBS_SOURCE_CAP_DISABLED;
  OBS_SOURCE_MONITOR_BY_DEFAULT = 1 SHL 11;
  OBS_SOURCE_SUBMIX = 1 SHL 12;
  OBS_SOURCE_CONTROLLABLE_MEDIA = 1 SHL 13;
  OBS_SOURCE_CEA_708 = 1 SHL 14;
  OBS_SOURCE_SRGB = 1 SHL 15;
  OBS_SOURCE_CAP_DONT_SHOW_PROPERTIES = 1 SHL 16;

  OBS_PROPERTIES_DEFER_UPDATE = 1 SHL 0;

  OBS_OUTPUT_VIDEO = 1 SHL 0;
  OBS_OUTPUT_AUDIO = 1 SHL 1;
  OBS_OUTPUT_AV = OBS_OUTPUT_VIDEO OR OBS_OUTPUT_AUDIO;
  OBS_OUTPUT_ENCODED = 1 SHL 2;
  OBS_OUTPUT_SERVICE = 1 SHL 3;
  OBS_OUTPUT_MULTI_TRACK = 1 SHL 4;
  OBS_OUTPUT_CAN_PAUSE = 1 SHL 5;
  OBS_OUTPUT_MULTI_TRACK_AUDIO = OBS_OUTPUT_MULTI_TRACK;
  OBS_OUTPUT_MULTI_TRACK_VIDEO = 1 SHL 6;
  OBS_OUTPUT_MULTI_TRACK_AV = OBS_OUTPUT_MULTI_TRACK_AUDIO OR OBS_OUTPUT_MULTI_TRACK_VIDEO;

  OBS_SERVICE_CONNECT_INFO_SERVER_URL = 0;
  OBS_SERVICE_CONNECT_INFO_STREAM_ID = 2;
  OBS_SERVICE_CONNECT_INFO_STREAM_KEY = OBS_SERVICE_CONNECT_INFO_STREAM_ID;
  OBS_SERVICE_CONNECT_INFO_USERNAME = 4;
  OBS_SERVICE_CONNECT_INFO_PASSWORD = 6;
  OBS_SERVICE_CONNECT_INFO_ENCRYPT_PASSPHRASE = 8;
  OBS_SERVICE_CONNECT_INFO_BEARER_TOKEN = 10;

  OBS_FONT_BOLD = 1 SHL 0;
  OBS_FONT_ITALIC = 1 SHL 1;
  OBS_FONT_UNDERLINE = 1 SHL 2;
  OBS_FONT_STRIKEOUT = 1 SHL 3;

  GS_FLIP_U = 1 SHL 0;
  GS_FLIP_V = 1 SHL 1;
  GS_CLEAR_COLOR = 1 SHL 0;
  GS_CLEAR_DEPTH = 1 SHL 1;
  GS_CLEAR_STENCIL = 1 SHL 2;
  GS_DEVICE_OPENGL = 1;
  GS_DEVICE_DIRECT3D_11 = 2;
  GS_DEVICE_METAL = 3;

type
  PPByte = ^PByte;
  POBSAnsiStringArray = ^TOBSAnsiStringArray;
  POBSVec2 = ^TOBSVec2;
  POBSVec3 = ^TOBSVec3;
  POBSVec4 = ^TOBSVec4;
  POBSQuat = ^TOBSQuat;
  POBSAxisAng = ^TOBSAxisAng;
  POBSMatrix3 = ^TOBSMatrix3;
  POBSMatrix4 = ^TOBSMatrix4;
  POBSMediaFramesPerSecond = ^TOBSMediaFramesPerSecond;
  POBSTransformInfo = ^TOBSTransformInfo;
  POBSPlane = ^TOBSPlane;
  POBSAudioConvertInfo = ^TOBSAudioConvertInfo;
  POBSGSRect = ^TOBSGSRect;
  POBSGSColorFormat = ^TOBSGSColorFormat;
  POBSGSColorSpace = ^TOBSGSColorSpace;
  POBSGSTVertArray = ^TOBSGSTVertArray;
  POBSGSVBData = ^TOBSGSVBData;
  POBSGSSamplerInfo = ^TOBSGSSamplerInfo;
  POBSGSTexture = ^TOBSGSTexture;
  POBSGSVertBuffer = ^TOBSGSVertBuffer;
  POBSGSZStencil = ^TOBSGSZStencil;

  TOBSAnsiStringArray = array[0..MaxInt div SizeOf(PAnsiChar) - 1] of PAnsiChar;

  TOBSVec2 = record
    X: Single;
    Y: Single;
  end;

  TOBSVec3 = record
    X: Single;
    Y: Single;
    Z: Single;
    W: Single;
  end;

  TOBSVec4 = record
    X: Single;
    Y: Single;
    Z: Single;
    W: Single;
  end;

  TOBSQuat = record
    X: Single;
    Y: Single;
    Z: Single;
    W: Single;
  end;

  TOBSAxisAng = record
    X: Single;
    Y: Single;
    Z: Single;
    W: Single;
  end;

  TOBSMatrix3 = record
    X: TOBSVec3;
    Y: TOBSVec3;
    Z: TOBSVec3;
    T: TOBSVec3;
  end;

  TOBSMatrix4 = record
    X: TOBSVec4;
    Y: TOBSVec4;
    Z: TOBSVec4;
    T: TOBSVec4;
  end;

  TOBSPlane = record
    Dir: TOBSVec3;
    Dist: Single;
  end;

  TOBSMediaFramesPerSecond = record
    Numerator: Cardinal;
    Denominator: Cardinal;
  end;

  TOBSGSTexture = record
  end;

  TOBSGSVertBuffer = record
  end;

  TOBSGSZStencil = record
  end;

  TOBSGSRect = record
    X: Integer;
    Y: Integer;
    CX: Integer;
    CY: Integer;
  end;

  TOBSGSTVertArray = record
    Width: NativeUInt;
    Data: Pointer;
  end;

  TOBSGSVBData = record
    Num: NativeUInt;
    Points: POBSVec3;
    Normals: POBSVec3;
    Tangents: POBSVec3;
    Colors: PCardinal;
    NumTex: NativeUInt;
    TVArray: POBSGSTVertArray;
  end;

  TOBSGSDrawMode = (
    GS_POINTS,
    GS_LINES,
    GS_LINESTRIP,
    GS_TRIS,
    GS_TRISTRIP
  );

  TOBSGSColorFormat = (
    GS_UNKNOWN,
    GS_A8,
    GS_R8,
    GS_RGBA,
    GS_BGRX,
    GS_BGRA,
    GS_R10G10B10A2,
    GS_RGBA16,
    GS_R16,
    GS_RGBA16F,
    GS_RGBA32F,
    GS_RG16F,
    GS_RG32F,
    GS_R16F,
    GS_R32F,
    GS_DXT1,
    GS_DXT3,
    GS_DXT5,
    GS_R8G8,
    GS_RGBA_UNORM,
    GS_BGRX_UNORM,
    GS_BGRA_UNORM,
    GS_RG16
  );

  TOBSGSColorSpace = (
    GS_CS_SRGB,
    GS_CS_SRGB_16F,
    GS_CS_709_EXTENDED,
    GS_CS_709_SCRGB
  );

  TOBSGSZStencilFormat = (
    GS_ZS_NONE,
    GS_Z16,
    GS_Z24_S8,
    GS_Z32F,
    GS_Z32F_S8X24
  );

  TOBSGSCubeSide = (
    GS_POSITIVE_X,
    GS_NEGATIVE_X,
    GS_POSITIVE_Y,
    GS_NEGATIVE_Y,
    GS_POSITIVE_Z,
    GS_NEGATIVE_Z
  );

  TOBSGSImageAlphaMode = (
    GS_IMAGE_ALPHA_STRAIGHT,
    GS_IMAGE_ALPHA_PREMULTIPLY_SRGB,
    GS_IMAGE_ALPHA_PREMULTIPLY
  );

  TOBSGSCullMode = (
    GS_BACK,
    GS_FRONT,
    GS_NEITHER
  );

  TOBSGSBlendType = (
    GS_BLEND_ZERO,
    GS_BLEND_ONE,
    GS_BLEND_SRCCOLOR,
    GS_BLEND_INVSRCCOLOR,
    GS_BLEND_SRCALPHA,
    GS_BLEND_INVSRCALPHA,
    GS_BLEND_DSTCOLOR,
    GS_BLEND_INVDSTCOLOR,
    GS_BLEND_DSTALPHA,
    GS_BLEND_INVDSTALPHA,
    GS_BLEND_SRCALPHASAT
  );

  TOBSGSBlendOpType = (
    GS_BLEND_OP_ADD,
    GS_BLEND_OP_SUBTRACT,
    GS_BLEND_OP_REVERSE_SUBTRACT,
    GS_BLEND_OP_MIN,
    GS_BLEND_OP_MAX
  );

  TOBSGSDepthTest = (
    GS_NEVER,
    GS_LESS,
    GS_LEQUAL,
    GS_EQUAL,
    GS_GEQUAL,
    GS_GREATER,
    GS_NOTEQUAL,
    GS_ALWAYS
  );

  TOBSGSStencilSide = (
    GS_STENCIL_FRONT = 1,
    GS_STENCIL_BACK,
    GS_STENCIL_BOTH
  );

  TOBSGSStencilOpType = (
    GS_KEEP,
    GS_ZERO,
    GS_REPLACE,
    GS_INCR,
    GS_DECR,
    GS_INVERT
  );

  TOBSGSTextureType = (
    GS_TEXTURE_2D,
    GS_TEXTURE_3D,
    GS_TEXTURE_CUBE
  );

  TOBSGSIndexType = (
    GS_UNSIGNED_SHORT,
    GS_UNSIGNED_LONG
  );

  TOBSGSSampleFilter = (
    GS_FILTER_POINT,
    GS_FILTER_LINEAR,
    GS_FILTER_ANISOTROPIC,
    GS_FILTER_MIN_MAG_POINT_MIP_LINEAR,
    GS_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT,
    GS_FILTER_MIN_POINT_MAG_MIP_LINEAR,
    GS_FILTER_MIN_LINEAR_MAG_MIP_POINT,
    GS_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR,
    GS_FILTER_MIN_MAG_LINEAR_MIP_POINT
  );

  TOBSGSAddressMode = (
    GS_ADDRESS_CLAMP,
    GS_ADDRESS_WRAP,
    GS_ADDRESS_MIRROR,
    GS_ADDRESS_BORDER,
    GS_ADDRESS_MIRRORONCE
  );

  TOBSGSSamplerInfo = record
    Filter: TOBSGSSampleFilter;
    AddressU: TOBSGSAddressMode;
    AddressV: TOBSGSAddressMode;
    AddressW: TOBSGSAddressMode;
    MaxAnisotropy: Integer;
    BorderColor: Cardinal;
  end;

  TOBSGSShaderParamType = (
    GS_SHADER_PARAM_UNKNOWN,
    GS_SHADER_PARAM_BOOL,
    GS_SHADER_PARAM_FLOAT,
    GS_SHADER_PARAM_INT,
    GS_SHADER_PARAM_STRING,
    GS_SHADER_PARAM_VEC2,
    GS_SHADER_PARAM_VEC3,
    GS_SHADER_PARAM_VEC4,
    GS_SHADER_PARAM_INT2,
    GS_SHADER_PARAM_INT3,
    GS_SHADER_PARAM_INT4,
    GS_SHADER_PARAM_MATRIX4X4,
    GS_SHADER_PARAM_TEXTURE
  );

  TOBSGSShaderType = (
    GS_SHADER_VERTEX,
    GS_SHADER_PIXEL
  );

  TOBSTaskType = (
    OBS_TASK_UI,
    OBS_TASK_GRAPHICS,
    OBS_TASK_AUDIO,
    OBS_TASK_DESTROY
  );

  POBSGSShaderParamInfo = ^TOBSGSShaderParamInfo;
  TOBSGSShaderParamInfo = record
    Typ: TOBSGSShaderParamType;
    Name: PAnsiChar;
  end;

  TOBSEncoderType = (
    OBS_ENCODER_AUDIO,
    OBS_ENCODER_VIDEO
  );

  TOBSObjType = (
    OBS_OBJ_TYPE_INVALID,
    OBS_OBJ_TYPE_SOURCE,
    OBS_OBJ_TYPE_OUTPUT,
    OBS_OBJ_TYPE_ENCODER,
    OBS_OBJ_TYPE_SERVICE,
    OBS_OBJ_TYPE_CANVAS
  );

  TOBSOrderMovement = (
    OBS_ORDER_MOVE_UP,
    OBS_ORDER_MOVE_DOWN,
    OBS_ORDER_MOVE_TOP,
    OBS_ORDER_MOVE_BOTTOM
  );

  TOBSAllowDirectRender = (
    OBS_NO_DIRECT_RENDERING,
    OBS_ALLOW_DIRECT_RENDERING
  );

  TOBSBaseEffect = (
    OBS_EFFECT_DEFAULT,
    OBS_EFFECT_DEFAULT_RECT,
    OBS_EFFECT_OPAQUE,
    OBS_EFFECT_SOLID,
    OBS_EFFECT_BICUBIC,
    OBS_EFFECT_LANCZOS,
    OBS_EFFECT_BILINEAR_LOWRES,
    OBS_EFFECT_PREMULTIPLIED_ALPHA,
    OBS_EFFECT_REPEAT,
    OBS_EFFECT_AREA
  );

  TOBSVideoFormat = (
    VIDEO_FORMAT_NONE,
    VIDEO_FORMAT_I420,
    VIDEO_FORMAT_NV12,
    VIDEO_FORMAT_YVYU,
    VIDEO_FORMAT_YUY2,
    VIDEO_FORMAT_UYVY,
    VIDEO_FORMAT_RGBA,
    VIDEO_FORMAT_BGRA,
    VIDEO_FORMAT_BGRX,
    VIDEO_FORMAT_Y800,
    VIDEO_FORMAT_I444,
    VIDEO_FORMAT_BGR3,
    VIDEO_FORMAT_I422,
    VIDEO_FORMAT_I40A,
    VIDEO_FORMAT_I42A,
    VIDEO_FORMAT_YUVA,
    VIDEO_FORMAT_AYUV,
    VIDEO_FORMAT_I010,
    VIDEO_FORMAT_P010,
    VIDEO_FORMAT_I210,
    VIDEO_FORMAT_I412,
    VIDEO_FORMAT_YA2L,
    VIDEO_FORMAT_P216,
    VIDEO_FORMAT_P416,
    VIDEO_FORMAT_V210,
    VIDEO_FORMAT_R10L
  );

  TOBSVideoTRC = (
    VIDEO_TRC_DEFAULT,
    VIDEO_TRC_SRGB,
    VIDEO_TRC_PQ,
    VIDEO_TRC_HLG
  );

  TOBSVideoColorspace = (
    VIDEO_CS_DEFAULT,
    VIDEO_CS_601,
    VIDEO_CS_709,
    VIDEO_CS_SRGB,
    VIDEO_CS_2100_PQ,
    VIDEO_CS_2100_HLG
  );

  TOBSVideoRangeType = (
    VIDEO_RANGE_DEFAULT,
    VIDEO_RANGE_PARTIAL,
    VIDEO_RANGE_FULL
  );

  TOBSScaleType = (
    OBS_SCALE_DISABLE,
    OBS_SCALE_POINT,
    OBS_SCALE_BICUBIC,
    OBS_SCALE_BILINEAR,
    OBS_SCALE_LANCZOS,
    OBS_SCALE_AREA
  );

  TOBSVideoscaleType = (
    VIDEO_SCALE_DEFAULT,
    VIDEO_SCALE_POINT,
    VIDEO_SCALE_FAST_BILINEAR,
    VIDEO_SCALE_BILINEAR,
    VIDEO_SCALE_BICUBIC
  );

  TOBSBlendingMethod = (
    OBS_BLEND_METHOD_DEFAULT,
    OBS_BLEND_METHOD_SRGB_OFF
  );

  TOBSBlendingType = (
    OBS_BLEND_NORMAL,
    OBS_BLEND_ADDITIVE,
    OBS_BLEND_SUBTRACT,
    OBS_BLEND_SCREEN,
    OBS_BLEND_MULTIPLY,
    OBS_BLEND_LIGHTEN,
    OBS_BLEND_DARKEN
  );

  TOBSBoundsType = (
    OBS_BOUNDS_NONE,
    OBS_BOUNDS_STRETCH,
    OBS_BOUNDS_SCALE_INNER,
    OBS_BOUNDS_SCALE_OUTER,
    OBS_BOUNDS_SCALE_TO_WIDTH,
    OBS_BOUNDS_SCALE_TO_HEIGHT,
    OBS_BOUNDS_MAX_ONLY
  );

  TOBSFrontendEvent = (
    OBS_FRONTEND_EVENT_STREAMING_STARTING,
    OBS_FRONTEND_EVENT_STREAMING_STARTED,
    OBS_FRONTEND_EVENT_STREAMING_STOPPING,
    OBS_FRONTEND_EVENT_STREAMING_STOPPED,
    OBS_FRONTEND_EVENT_RECORDING_STARTING,
    OBS_FRONTEND_EVENT_RECORDING_STARTED,
    OBS_FRONTEND_EVENT_RECORDING_STOPPING,
    OBS_FRONTEND_EVENT_RECORDING_STOPPED,
    OBS_FRONTEND_EVENT_SCENE_CHANGED,
    OBS_FRONTEND_EVENT_SCENE_LIST_CHANGED,
    OBS_FRONTEND_EVENT_TRANSITION_CHANGED,
    OBS_FRONTEND_EVENT_TRANSITION_STOPPED,
    OBS_FRONTEND_EVENT_TRANSITION_LIST_CHANGED,
    OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGED,
    OBS_FRONTEND_EVENT_SCENE_COLLECTION_LIST_CHANGED,
    OBS_FRONTEND_EVENT_PROFILE_CHANGED,
    OBS_FRONTEND_EVENT_PROFILE_LIST_CHANGED,
    OBS_FRONTEND_EVENT_EXIT,

    OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTING,
    OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTED,
    OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPING,
    OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPED,

    OBS_FRONTEND_EVENT_STUDIO_MODE_ENABLED,
    OBS_FRONTEND_EVENT_STUDIO_MODE_DISABLED,
    OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED,

    OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP,
    OBS_FRONTEND_EVENT_FINISHED_LOADING,

    OBS_FRONTEND_EVENT_RECORDING_PAUSED,
    OBS_FRONTEND_EVENT_RECORDING_UNPAUSED,

    OBS_FRONTEND_EVENT_TRANSITION_DURATION_CHANGED,
    OBS_FRONTEND_EVENT_REPLAY_BUFFER_SAVED,

    OBS_FRONTEND_EVENT_VIRTUALCAM_STARTED,
    OBS_FRONTEND_EVENT_VIRTUALCAM_STOPPED,

    OBS_FRONTEND_EVENT_TBAR_VALUE_CHANGED,
    OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGING,
    OBS_FRONTEND_EVENT_PROFILE_CHANGING,
    OBS_FRONTEND_EVENT_SCRIPTING_SHUTDOWN,
    OBS_FRONTEND_EVENT_PROFILE_RENAMED,
    OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED,
    OBS_FRONTEND_EVENT_THEME_CHANGED,
    OBS_FRONTEND_EVENT_SCREENSHOT_TAKEN
  );

  TOBSAudioFormat = (
    AUDIO_FORMAT_UNKNOWN,

    AUDIO_FORMAT_U8BIT,
    AUDIO_FORMAT_16BIT,
    AUDIO_FORMAT_32BIT,
    AUDIO_FORMAT_FLOAT,

    AUDIO_FORMAT_U8BIT_PLANAR,
    AUDIO_FORMAT_16BIT_PLANAR,
    AUDIO_FORMAT_32BIT_PLANAR,
    AUDIO_FORMAT_FLOAT_PLANAR
  );

  TOBSSpeakerLayout = (
    SPEAKERS_UNKNOWN,
    SPEAKERS_MONO,
    SPEAKERS_STEREO,
    SPEAKERS_2POINT1,
    SPEAKERS_4POINT0,
    SPEAKERS_4POINT1,
    SPEAKERS_5POINT1,
    SPEAKERS_7POINT1 = 8
  );

  TOBSAudioConvertInfo = record
    SamplesPerSec: Cardinal;
    Format: TOBSAudioFormat;
    Speakers: TOBSSpeakerLayout;
    AllowClipping: Boolean;
  end;

  TOBSSourceType = (
    OBS_SOURCE_TYPE_INPUT,
    OBS_SOURCE_TYPE_FILTER,
    OBS_SOURCE_TYPE_TRANSITION,
    OBS_SOURCE_TYPE_SCENE
  );

  TOBSBalanceType = (
    OBS_BALANCE_TYPE_SINE_LAW,
    OBS_BALANCE_TYPE_SQUARE_LAW,
    OBS_BALANCE_TYPE_LINEAR
  );

  TOBSIconType = (
    OBS_ICON_TYPE_UNKNOWN,
    OBS_ICON_TYPE_IMAGE,
    OBS_ICON_TYPE_COLOR,
    OBS_ICON_TYPE_SLIDESHOW,
    OBS_ICON_TYPE_AUDIO_INPUT,
    OBS_ICON_TYPE_AUDIO_OUTPUT,
    OBS_ICON_TYPE_DESKTOP_CAPTURE,
    OBS_ICON_TYPE_WINDOW_CAPTURE,
    OBS_ICON_TYPE_GAME_CAPTURE,
    OBS_ICON_TYPE_CAMERA,
    OBS_ICON_TYPE_TEXT,
    OBS_ICON_TYPE_MEDIA,
    OBS_ICON_TYPE_BROWSER,
    OBS_ICON_TYPE_CUSTOM,
    OBS_ICON_TYPE_PROCESS_AUDIO_OUTPUT
  );

  TOBSMediaState = (
    OBS_MEDIA_STATE_NONE,
    OBS_MEDIA_STATE_PLAYING,
    OBS_MEDIA_STATE_OPENING,
    OBS_MEDIA_STATE_BUFFERING,
    OBS_MEDIA_STATE_PAUSED,
    OBS_MEDIA_STATE_STOPPED,
    OBS_MEDIA_STATE_ENDED,
    OBS_MEDIA_STATE_ERROR
  );

  TOBSModuleLoadState = (
    OBS_MODULE_INVALID,
    OBS_MODULE_ENABLED,
    OBS_MODULE_MISSING,
    OBS_MODULE_DISABLED,
    OBS_MODULE_DISABLED_SAFE,
    OBS_MODULE_FAILED_TO_OPEN,
    OBS_MODULE_FAILED_TO_INITIALIZE
  );

  TOBSDeinterlaceMode = (
    OBS_DEINTERLACE_MODE_DISABLE,
    OBS_DEINTERLACE_MODE_DISCARD,
    OBS_DEINTERLACE_MODE_RETRO,
    OBS_DEINTERLACE_MODE_BLEND,
    OBS_DEINTERLACE_MODE_BLEND_2X,
    OBS_DEINTERLACE_MODE_LINEAR,
    OBS_DEINTERLACE_MODE_LINEAR_2X,
    OBS_DEINTERLACE_MODE_YADIF,
    OBS_DEINTERLACE_MODE_YADIF_2X
  );

  TOBSDeinterlaceFieldOrder = (
    OBS_DEINTERLACE_FIELD_ORDER_TOP,
    OBS_DEINTERLACE_FIELD_ORDER_BOTTOM
  );

  TOBSMonitoringType = (
    OBS_MONITORING_TYPE_NONE,
    OBS_MONITORING_TYPE_MONITOR_ONLY,
    OBS_MONITORING_TYPE_MONITOR_AND_OUTPUT
  );

  TOBSTransitionTarget = (
    OBS_TRANSITION_SOURCE_A,
    OBS_TRANSITION_SOURCE_B
  );

  TOBSTransitionMode = (
    OBS_TRANSITION_MODE_AUTO,
    OBS_TRANSITION_MODE_MANUAL
  );

  TOBSTransitionScaleType = (
    OBS_TRANSITION_SCALE_MAX_ONLY,
    OBS_TRANSITION_SCALE_ASPECT,
    OBS_TRANSITION_SCALE_STRETCH
  );

  TOBSSceneDuplicateType = (
    OBS_SCENE_DUP_REFS,
    OBS_SCENE_DUP_COPY,
    OBS_SCENE_DUP_PRIVATE_REFS,
    OBS_SCENE_DUP_PRIVATE_COPY
  );

  TOBSTransformInfo = record
    Pos: TOBSVec2;
    Rot: Single;
    Scale: TOBSVec2;
    Alignment: Cardinal;
    BoundsType: TOBSBoundsType;
    BoundsAlignment: Cardinal;
    Bounds: TOBSVec2;
    CropToBounds: Boolean;
  end;

  TOBSDataType = (
    OBS_DATA_NULL,
    OBS_DATA_STRING,
    OBS_DATA_NUMBER,
    OBS_DATA_BOOLEAN,
    OBS_DATA_OBJECT,
    OBS_DATA_ARRAY
  );

  TOBSDataNumberType = (
    OBS_DATA_NUM_INVALID,
    OBS_DATA_NUM_INT,
    OBS_DATA_NUM_DOUBLE
  );

type // obs-properties.h
  TOBSPropertyType = (
    OBS_PROPERTY_INVALID,
    OBS_PROPERTY_BOOL,
    OBS_PROPERTY_INT,
    OBS_PROPERTY_FLOAT,
    OBS_PROPERTY_TEXT,
    OBS_PROPERTY_PATH,
    OBS_PROPERTY_LIST,
    OBS_PROPERTY_COLOR,
    OBS_PROPERTY_BUTTON,
    OBS_PROPERTY_FONT,
    OBS_PROPERTY_EDITABLE_LIST,
    OBS_PROPERTY_FRAME_RATE,
    OBS_PROPERTY_GROUP,
    OBS_PROPERTY_COLOR_ALPHA
  );

  TOBSComboFormat = (
    OBS_COMBO_FORMAT_INVALID,
    OBS_COMBO_FORMAT_INT,
    OBS_COMBO_FORMAT_FLOAT,
    OBS_COMBO_FORMAT_STRING,
    OBS_COMBO_FORMAT_BOOL
  );

  TOBSComboType = (
    OBS_COMBO_TYPE_INVALID,
    OBS_COMBO_TYPE_EDITABLE,
    OBS_COMBO_TYPE_LIST,
    OBS_COMBO_TYPE_RADIO
  );

  TOBSEditableListType = (
    OBS_EDITABLE_LIST_TYPE_STRINGS,
    OBS_EDITABLE_LIST_TYPE_FILES,
    OBS_EDITABLE_LIST_TYPE_FILES_AND_URLS
  );

  TOBSPathType = (
    OBS_PATH_FILE,
    OBS_PATH_FILE_SAVE,
    OBS_PATH_DIRECTORY
  );

  TOBSTextType = (
    OBS_TEXT_DEFAULT,
    OBS_TEXT_PASSWORD,
    OBS_TEXT_MULTILINE,
    OBS_TEXT_INFO
  );

  TOBSTextInfoType = (
    OBS_TEXT_INFO_NORMAL,
    OBS_TEXT_INFO_WARNING,
    OBS_TEXT_INFO_ERROR
  );

  TOBSNumberType = (
    OBS_NUMBER_SCROLLER,
    OBS_NUMBER_SLIDER
  );

  TOBSGroupType = (
    OBS_COMBO_INVALID,
    OBS_GROUP_NORMAL,
    OBS_GROUP_CHECKABLE
  );

  TOBSButtonType = (
    OBS_BUTTON_DEFAULT,
    OBS_BUTTON_URL
  );

type //
  TOBSDArray<TDataType> = record
    Data: ^TDataType;
    Num: UInt64;
    Capacity: UInt64;
  end;

implementation

end.
