unit XENOME.OBS.Source;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, System.Win.Registry, System.IniFiles, System.Generics.Defaults, System.Generics.Collections,
  System.Contnrs, System.SyncObjs, XENOME.OBS, XENOME.OBS.Types, XENOME.OBS.Video, XENOME.OBS.Data, XENOME.OBS.Audio, XENOME.OBS.Properties, XENOME.OBS.Graphics;

type
  PPOBSSceneItem = ^POBSSceneItem;

  TOBSSourceProc<TParam> = procedure(Param: TParam) cdecl;
  TOBSSourceProc2<TParam,TParam2> = procedure(Param: TParam; Param2: TParam2) cdecl;
  TOBSSourceProc3<TParam,TParam2,TParam3> = procedure(Param: TParam; Param2: TParam2; Param3: TParam3) cdecl;
  TOBSSourceProc4<TParam,TParam2,TParam3,TParam4> = procedure(Param: TParam; Param2: TParam2; Param3: TParam3; Param4: TParam4) cdecl;
  TOBSSourceProc5<TParam,TParam2,TParam3,TParam4,TParam5> = procedure(Param: TParam; Param2: TParam2; Param3: TParam3; Param4: TParam4; Param5: TParam5) cdecl;
  TOBSSourceFunc<TResult,TParam> = function(Param: TParam): TResult cdecl;
  TOBSSourceFunc2<TResult,TParam,TParam2> = function(Param: TParam; Param2: TParam2): TResult cdecl;
  TOBSSourceFunc3<TResult,TParam,TParam2,TParam3> = function(Param: TParam; Param2: TParam2; Param3: TParam3): TResult cdecl;
  TOBSSourceFunc4<TResult,TParam,TParam2,TParam3,TParam4> = function(Param: TParam; Param2: TParam2; Param3: TParam3; Param4: TParam4): TResult cdecl;
  TOBSSourceFunc5<TResult,TParam,TParam2,TParam3,TParam4,TParam5> = function(Param: TParam; Param2: TParam2; Param3: TParam3; Param4: TParam4; Param5: TParam5): TResult cdecl;
  TOBSSourceFunc6<TResult,TParam,TParam2,TParam3,TParam4,TParam5,TParam6> = function(Param: TParam; Param2: TParam2; Param3: TParam3; Param4: TParam4; Param5: TParam5; Param6: TParam6): TResult cdecl;
  TOBSSourceGetNameFunc = function(TypeData: Pointer): PAnsiChar cdecl;
  TOBSSourceCreateFunc = function(Settings: POBSData; Source: POBSSource): Pointer cdecl;
  TOBSSourceDestroyProc = procedure(Data: Pointer) cdecl;

  TOBSSourceEnumCallback = procedure(Parent, Child: POBSSource; Param: Pointer) cdecl;
  POBSSourceEnumCallback = TOBSSourceEnumCallback;

  POBSSourceAudioMix = ^TOBSSourceAudioMix;
  TOBSSourceAudioMix = record
    Output: Array[0..MAX_AUDIO_MIXES-1] of TOBSAudioOutputData;
  end;

  POBSSourceAudio = ^TOBSSourceAudio;
  TOBSSourceAudio = record
    Data: Array[0..MAX_AV_PLANES-1] of PByte;
    Frames: Cardinal;
    Speakers: TOBSSpeakerLayout;
    Format: TOBSAudioFormat;
    SamplesPerSec: Cardinal;
    TimeStamp: UInt64;
  end;

  POBSSourceCEA708 = ^TOBSSourceCEA708;
  TOBSSourceCEA708 = record
    Data: PByte;
    Packets: Cardinal;
    TimeStamp: UInt64;
  end;

  TOBSMissingFileCallback = procedure(Src: Pointer; NewPath: PAnsiChar; Data: Pointer) cdecl;
  TOBSSourceAudioCaptureCallback = procedure(Param: Pointer; Source: POBSSource; AudioData: POBSAudioData; Muted: Boolean) cdecl;
  TOBSSourceCaptionCallback = procedure(Param: Pointer; Source: POBSSource; Captions: POBSSourceCEA708) cdecl;
  TOBSSceneEnumItemsCallback = function(Scene: POBSScene; Item: POBSSceneItem; Param: Pointer): Boolean cdecl;
  TOBSSceneAtomicUpdateFunc = procedure(Data: Pointer; Scene: POBSScene) cdecl;
  TOBSTransitionVideoRenderCallback = procedure(Data: Pointer; ATexture, BTexture: POBSGSTexture; T: Single; CX, CY: Cardinal) cdecl;
  TOBSTransitionAudioMixCallback = function(Data: Pointer; T: Single): Single cdecl;

  POBSSceneItemOrderInfo = ^TOBSSceneItemOrderInfo;
  TOBSSceneItemOrderInfo = record
    Group: POBSSceneItem;
    Item: POBSSceneItem;
  end;

  POBSSceneItemCrop = ^TOBSSceneItemCrop;
  TOBSSceneItemCrop = record
    Left: Integer;
    Top: Integer;
    Right: Integer;
    Bottom: Integer;
  end;

  POBSMouseEvent = ^TOBSMouseEvent;
  TOBSMouseEvent = record
    Modifiers: Cardinal;
    X: Int32;
    Y: Int32;
  end;
  POBSKeyEvent = ^TOBSKeyEvent;
  TOBSKeyEvent = record
    Modifiers: Cardinal;
    Text: PAnsiChar;
    NativeModifiers: Cardinal;
    NativeScancode: Cardinal;
    NativeVKey: Cardinal;
  end;

  POBSMissingFiles = ^TOBSMissingFiles;
  TOBSMissingFiles = record
  end;

  POBSSourceFrame = ^TOBSSourceFrame;
  TOBSSourceFrame = record
    Data: Array[0..MAX_AV_PLANES-1] of PByte;
    LineSize: Array[0..MAX_AV_PLANES-1] of Cardinal;
    Width: Cardinal;
    Height: Cardinal;
    TimeStamp: UInt64;
    Format: TOBSVideoFormat;
    ColorMatrix: Array[0..15] of Single;
    FullRange: Boolean;
    MaxLuminance: Word;
    ColorRangeMin: Array[0..2] of Single;
    ColorRangeMax: Array[0..2] of Single;
    Flip: Boolean;
    Flags: Byte;
    TRC: Byte;
    Refs: Longint;
    PrevFrame: Boolean;
  end;

  POBSSourceFrame2 = ^TOBSSourceFrame2;
  TOBSSourceFrame2 = record
    Data: Array[0..MAX_AV_PLANES-1] of PByte;
    LineSize: Array[0..MAX_AV_PLANES-1] of Cardinal;
    Width: Cardinal;
    Height: Cardinal;
    TimeStamp: UInt64;
    Format: TOBSVideoFormat;
    Range: TOBSVideoRangeType;
    ColorMatrix: Array[0..15] of Single;
    ColorRangeMin: Array[0..2] of Single;
    ColorRangeMax: Array[0..2] of Single;
    Flip: Boolean;
    Flags: Byte;
    TRC: Byte;
  end;

  POBSSourceInfo = ^TOBSSourceInfo;
  TOBSSourceInfo = record
    Id: PAnsiChar;
    Typ: TOBSSourceType;
    OutputFlags: Cardinal;
    GetName: TOBSSourceGetNameFunc;
    Create: TOBSSourceCreateFunc;
    Destroy: TOBSSourceDestroyProc;
    GetWidth: TOBSSourceFunc<Cardinal,Pointer>;
    GetHeight: TOBSSourceFunc<Cardinal,Pointer>;
    GetDefaults: TOBSSourceProc<POBSData>;
    GetProperties: TOBSSourceFunc<POBSProperties,Pointer>;
    Update: TOBSSourceProc2<Pointer,POBSData>;
    Activate: TOBSSourceProc<Pointer>;
    Deactivate: TOBSSourceProc<Pointer>;
    Show: TOBSSourceProc<Pointer>;
    Hide: TOBSSourceProc<Pointer>;
    VideoTick: TOBSSourceProc2<Pointer,Single>;
    VideoRender: TOBSSourceProc2<Pointer,POBSGSEffect>;
    FilterVideo: TOBSSourceFunc2<POBSSourceFrame,Pointer,POBSSourceFrame>;
    FilterAudio: TOBSSourceFunc2<POBSAudioData,Pointer,POBSAudioData>;
    EnumActiveSources: TOBSSourceProc3<Pointer,TOBSSourceEnumCallback,Pointer>;
    Save: TOBSSourceProc2<Pointer,POBSData>;
    Load: TOBSSourceProc2<Pointer,POBSData>;
    MouseClick: TOBSSourceProc5<Pointer,POBSMouseEvent,Integer,Boolean,Cardinal>;
    MouseMove: TOBSSourceProc3<Pointer,POBSMouseEvent,Boolean>;
    MouseWheel: TOBSSourceProc4<Pointer,POBSMouseEvent,Integer,Integer>;
    Focus: TOBSSourceProc2<Pointer,Boolean>;
    KeyClick: TOBSSourceProc3<Pointer,POBSKeyEvent,Boolean>;
    FilterRemove: TOBSSourceProc2<Pointer,POBSSource>;
    TypeData: Pointer;
    FreeTypeData: TOBSSourceProc<Pointer>;
    AudioRender: TOBSSourceFunc6<Boolean,Pointer,PUInt64,POBSSourceAudioMix,Cardinal,NativeUInt,NativeUInt>;
    EnumAllSources: TOBSSourceProc3<Pointer,TOBSSourceEnumCallback,Pointer>;
    TransitionStart: TOBSSourceProc<Pointer>;
    TransitionStop: TOBSSourceProc<Pointer>;
    GetDefaults2: TOBSSourceProc2<Pointer,POBSData>;
    GetProperties2: TOBSSourceFunc2<POBSProperties,Pointer,Pointer>;
    AudioMix: TOBSSourceFunc5<Boolean,Pointer,PUInt64,POBSAudioOutputData,NativeUInt,NativeUInt>;
    IconType: TOBSIconType;
    MediaPlayPause: TOBSSourceProc2<Pointer,Boolean>;
    MediaRestart: TOBSSourceProc<Pointer>;
    MediaStop: TOBSSourceProc<Pointer>;
    MediaNext: TOBSSourceProc<Pointer>;
    MediaPrevious: TOBSSourceProc<Pointer>;
    MediaGetduration: TOBSSourceFunc<Int64,Pointer>;
    MediaGetTime: TOBSSourceFunc<Int64,Pointer>;
    MediaSetTime: TOBSSourceProc2<Pointer,Int64>;
    MediaGetState: TOBSSourceFunc<TOBSMediaState,Pointer>;
    Version: Cardinal;
    UnversionedId: PAnsiChar;
    MissingFiles: TOBSSourceFunc<POBSMissingFiles,Pointer>;
    VideoGetColorSpace: TOBSSourceFunc3<TOBSGSColorSpace,Pointer,NativeUInt,POBSGSColorSpace>;
    FilterAdd: TOBSSourceProc2<Pointer,POBSSource>;
    GetDarkIcon: TOBSSourceFunc<PAnsiChar,Pointer>;
    GetLightIcon: TOBSSourceFunc<PAnsiChar,Pointer>;
  end;

procedure obs_register_source_s(AInfo: POBSSourceInfo; ASize: NativeUInt); cdecl; external 'obs.dll' name 'obs_register_source_s';
procedure obs_register_source(AInfo: POBSSourceInfo);
procedure obs_set_output_source(AChannel: Cardinal; ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_set_output_source';
function obs_get_output_source(AChannel: Cardinal): POBSSource; cdecl; external 'obs.dll' name 'obs_get_output_source';
function obs_get_source_by_name(AName: PAnsiChar): POBSSource; cdecl; external 'obs.dll' name 'obs_get_source_by_name';
function obs_get_source_by_uuid(AUuid: PAnsiChar): POBSSource; cdecl; external 'obs.dll' name 'obs_get_source_by_uuid';
function obs_save_source(ASource: POBSSource): POBSData; cdecl; external 'obs.dll' name 'obs_save_source';
function obs_load_source(AData: POBSData): POBSSource; cdecl; external 'obs.dll' name 'obs_load_source';
function obs_load_private_source(AData: POBSData): POBSSource; cdecl; external 'obs.dll' name 'obs_load_private_source';
procedure obs_source_save(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_save';
procedure obs_source_load(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_load';
procedure obs_source_load2(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_load2';
function obs_source_get_display_name(AId: PAnsiChar): PAnsiChar; cdecl; external 'obs.dll' name 'obs_source_get_display_name';
function obs_source_get_module(AId: PAnsiChar): POBSModule; cdecl; external 'obs.dll' name 'obs_source_get_module';
function obs_source_load_state(AId: PAnsiChar): TOBSModuleLoadState; cdecl; external 'obs.dll' name 'obs_source_load_state';
function obs_source_create(AId, AName: PAnsiChar; ASettings, AHotkeyData: POBSData): POBSSource; cdecl; external 'obs.dll' name 'obs_source_create';
function obs_source_create_private(AId, AName: PAnsiChar; ASettings: POBSData): POBSSource; cdecl; external 'obs.dll' name 'obs_source_create_private';
function obs_source_duplicate(ASource: POBSSource; ADesiredName: PAnsiChar; ACreatePrivate: Boolean): POBSSource; cdecl; external 'obs.dll' name 'obs_source_duplicate';
procedure obs_source_release(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_release';
procedure obs_weak_source_addref(AWeak: POBSWeakSource); cdecl; external 'obs.dll' name 'obs_weak_source_addref';
procedure obs_weak_source_release(AWeak: POBSWeakSource); cdecl; external 'obs.dll' name 'obs_weak_source_release';
function obs_source_get_ref(ASource: POBSSource): POBSSource; cdecl; external 'obs.dll' name 'obs_source_get_ref';
function obs_source_get_weak_source(ASource: POBSSource): POBSWeakSource; cdecl; external 'obs.dll' name 'obs_source_get_weak_source';
function obs_weak_source_get_source(AWeak: POBSWeakSource): POBSSource; cdecl; external 'obs.dll' name 'obs_weak_source_get_source';
function obs_weak_source_expired(AWeak: POBSWeakSource): Boolean; cdecl; external 'obs.dll' name 'obs_weak_source_expired';
function obs_weak_source_references_source(AWeak: POBSWeakSource; ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_weak_source_references_source';
procedure obs_source_remove(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_remove';
function obs_source_removed(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_removed';
procedure obs_source_set_hidden(ASource: POBSSource; AHidden: Boolean); cdecl; external 'obs.dll' name 'obs_source_set_hidden';
function obs_source_is_hidden(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_is_hidden';
function obs_source_get_output_flags(ASource: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_source_get_output_flags';
function obs_get_source_output_flags(AId: PAnsiChar): Cardinal; cdecl; external 'obs.dll' name 'obs_get_source_output_flags';
function obs_get_source_defaults(AId: PAnsiChar): POBSData; cdecl; external 'obs.dll' name 'obs_get_source_defaults';
function obs_get_source_properties(AId: PAnsiChar): POBSProperties; cdecl; external 'obs.dll' name 'obs_get_source_properties';
function obs_source_get_missing_files(ASource: POBSSource): POBSMissingFiles; cdecl; external 'obs.dll' name 'obs_source_get_missing_files';
procedure obs_source_replace_missing_file(ACallback: TOBSMissingFileCallback; ASource: POBSSource; ANewPath: PAnsiChar; AData: Pointer); cdecl; external 'obs.dll' name 'obs_source_replace_missing_file';
function obs_is_source_configurable(AId: PAnsiChar): Boolean; cdecl; external 'obs.dll' name 'obs_is_source_configurable';
function obs_source_configurable(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_configurable';
function obs_source_properties(ASource: POBSSource): POBSProperties; cdecl; external 'obs.dll' name 'obs_source_properties';
procedure obs_source_update(ASource: POBSSource; ASettings: POBSData); cdecl; external 'obs.dll' name 'obs_source_update';
procedure obs_source_reset_settings(ASource: POBSSource; ASettings: POBSData); cdecl; external 'obs.dll' name 'obs_source_reset_settings';
procedure obs_source_video_render(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_video_render';
function obs_source_get_width(ASource: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_source_get_width';
function obs_source_get_height(ASource: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_source_get_height';
function obs_source_get_color_space(ASource: POBSSource; ACount: NativeUInt; APreferredSpaces: POBSGSColorSpace): TOBSGSColorSpace; cdecl; external 'obs.dll' name 'obs_source_get_color_space';
function obs_source_get_texcoords_centered(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_get_texcoords_centered';
function obs_filter_get_parent(AFilter: POBSSource): POBSSource; cdecl; external 'obs.dll' name 'obs_filter_get_parent';
function obs_filter_get_target(AFilter: POBSSource): POBSSource; cdecl; external 'obs.dll' name 'obs_filter_get_target';
procedure obs_source_default_render(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_default_render';
procedure obs_source_filter_add(ASource: POBSSource; AFilter: POBSSource); cdecl; external 'obs.dll' name 'obs_source_filter_add';
procedure obs_source_filter_remove(ASource: POBSSource; AFilter: POBSSource); cdecl; external 'obs.dll' name 'obs_source_filter_remove';
procedure obs_source_filter_set_order(ASource: POBSSource; AFilter: POBSSource; AMovement: TOBSOrderMovement); cdecl; external 'obs.dll' name 'obs_source_filter_set_order';
function obs_source_filter_get_index(ASource: POBSSource; AFilter: POBSSource): Integer; cdecl; external 'obs.dll' name 'obs_source_filter_get_index';
procedure obs_source_filter_set_index(ASource: POBSSource; AFilter: POBSSource; AIndex: NativeUInt); cdecl; external 'obs.dll' name 'obs_source_filter_set_index';
function obs_source_get_settings(ASource: POBSSource): POBSData; cdecl; external 'obs.dll' name 'obs_source_get_settings';
function obs_source_get_name(ASource: POBSSource): PAnsiChar; cdecl; external 'obs.dll' name 'obs_source_get_name';
procedure obs_source_set_name(ASource: POBSSource; AName: PAnsiChar); cdecl; external 'obs.dll' name 'obs_source_set_name';
function obs_source_get_uuid(ASource: POBSSource): PAnsiChar; cdecl; external 'obs.dll' name 'obs_source_get_uuid';
function obs_source_get_type(ASource: POBSSource): TOBSSourceType; cdecl; external 'obs.dll' name 'obs_source_get_type';
function obs_source_get_id(ASource: POBSSource): PAnsiChar; cdecl; external 'obs.dll' name 'obs_source_get_id';
function obs_source_get_unversioned_id(ASource: POBSSource): PAnsiChar; cdecl; external 'obs.dll' name 'obs_source_get_unversioned_id';
function obs_source_get_signal_handler(ASource: POBSSource): POBSSignalHandler; cdecl; external 'obs.dll' name 'obs_source_get_signal_handler';
function obs_source_get_proc_handler(ASource: POBSSource): POBSProcHandler; cdecl; external 'obs.dll' name 'obs_source_get_proc_handler';
procedure obs_source_set_volume(ASource: POBSSource; AVolume: Single); cdecl; external 'obs.dll' name 'obs_source_set_volume';
function obs_source_get_volume(ASource: POBSSource): Single; cdecl; external 'obs.dll' name 'obs_source_get_volume';
function obs_source_get_speaker_layout(ASource: POBSSource): TOBSSpeakerLayout; cdecl; external 'obs.dll' name 'obs_source_get_speaker_layout';
procedure obs_source_set_balance_value(ASource: POBSSource; ABalance: Single); cdecl; external 'obs.dll' name 'obs_source_set_balance_value';
function obs_source_get_balance_value(ASource: POBSSource): Single; cdecl; external 'obs.dll' name 'obs_source_get_balance_value';
procedure obs_source_set_sync_offset(ASource: POBSSource; AOffset: Int64); cdecl; external 'obs.dll' name 'obs_source_set_sync_offset';
function obs_source_get_sync_offset(ASource: POBSSource): Int64; cdecl; external 'obs.dll' name 'obs_source_get_sync_offset';
procedure obs_source_enum_active_sources(ASource: POBSSource; AEnumCallback: TOBSSourceEnumCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_source_enum_active_sources';
procedure obs_source_enum_active_tree(ASource: POBSSource; AEnumCallback: TOBSSourceEnumCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_source_enum_active_tree';
procedure obs_source_enum_full_tree(ASource: POBSSource; AEnumCallback: TOBSSourceEnumCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_source_enum_full_tree';
function obs_source_active(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_active';
function obs_source_showing(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_showing';
procedure obs_source_set_flags(ASource: POBSSource; AFlags: Cardinal); cdecl; external 'obs.dll' name 'obs_source_set_flags';
function obs_source_get_flags(ASource: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_source_get_flags';
procedure obs_source_set_audio_mixers(ASource: POBSSource; AMixers: Cardinal); cdecl; external 'obs.dll' name 'obs_source_set_audio_mixers';
function obs_source_get_audio_mixers(ASource: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_source_get_audio_mixers';
procedure obs_source_inc_showing(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_inc_showing';
procedure obs_source_inc_active(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_inc_active';
procedure obs_source_dec_showing(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_dec_showing';
procedure obs_source_dec_active(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_dec_active';
procedure obs_source_enum_filters(ASource: POBSSource; ACallback: TOBSSourceEnumCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_source_enum_filters';
function obs_source_get_filter_by_name(ASource: POBSSource; AName: PAnsiChar): POBSSource; cdecl; external 'obs.dll' name 'obs_source_get_filter_by_name';
function obs_source_filter_count(ASource: POBSSource): NativeUInt; cdecl; external 'obs.dll' name 'obs_source_filter_count';
procedure obs_source_copy_filters(ADst: POBSSource; ASrc: POBSSource); cdecl; external 'obs.dll' name 'obs_source_copy_filters';
procedure obs_source_copy_single_filter(ADst: POBSSource; AFilter: POBSSource); cdecl; external 'obs.dll' name 'obs_source_copy_single_filter';
function obs_source_enabled(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_enabled';
procedure obs_source_set_enabled(ASource: POBSSource; AEnabled: Boolean); cdecl; external 'obs.dll' name 'obs_source_set_enabled';
function obs_source_muted(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_muted';
procedure obs_source_set_muted(ASource: POBSSource; AMuted: Boolean); cdecl; external 'obs.dll' name 'obs_source_set_muted';
function obs_source_push_to_mute_enabled(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_push_to_mute_enabled';
procedure obs_source_enable_push_to_mute(ASource: POBSSource; AEnabled: Boolean); cdecl; external 'obs.dll' name 'obs_source_enable_push_to_mute';
function obs_source_get_push_to_mute_delay(ASource: POBSSource): UInt64; cdecl; external 'obs.dll' name 'obs_source_get_push_to_mute_delay';
procedure obs_source_set_push_to_mute_delay(ASource: POBSSource; ADelay: UInt64); cdecl; external 'obs.dll' name 'obs_source_set_push_to_mute_delay';
function obs_source_push_to_talk_enabled(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_push_to_talk_enabled';
procedure obs_source_enable_push_to_talk(ASource: POBSSource; AEnabled: Boolean); cdecl; external 'obs.dll' name 'obs_source_enable_push_to_talk';
function obs_source_get_push_to_talk_delay(ASource: POBSSource): UInt64; cdecl; external 'obs.dll' name 'obs_source_get_push_to_talk_delay';
procedure obs_source_set_push_to_talk_delay(ASource: POBSSource; ADelay: UInt64); cdecl; external 'obs.dll' name 'obs_source_set_push_to_talk_delay';
procedure obs_source_add_audio_capture_callback(ASource: POBSSource; ACallback: TOBSSourceAudioCaptureCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_source_add_audio_capture_callback';
procedure obs_source_remove_audio_capture_callback(ASource: POBSSource; ACallback: TOBSSourceAudioCaptureCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_source_remove_audio_capture_callback';
procedure obs_source_audio_output_capture_device_changed(ASource: POBSSource; ADeviceId: PAnsiChar); cdecl; external 'obs.dll' name 'obs_source_audio_output_capture_device_changed';
procedure obs_source_add_caption_callback(ASource: POBSSource; ACallback: TOBSSourceCaptionCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_source_add_caption_callback';
procedure obs_source_remove_caption_callback(ASource: POBSSource; ACallback: TOBSSourceCaptionCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_source_remove_caption_callback';
procedure obs_source_set_deinterlace_mode(ASource: POBSSource; AMode: TOBSDeinterlaceMode); cdecl; external 'obs.dll' name 'obs_source_set_deinterlace_mode';
function obs_source_get_deinterlace_mode(ASource: POBSSource): TOBSDeinterlaceMode; cdecl; external 'obs.dll' name 'obs_source_get_deinterlace_mode';
procedure obs_source_set_deinterlace_field_order(ASource: POBSSource; AFieldOrder: TOBSDeinterlaceFieldOrder); cdecl; external 'obs.dll' name 'obs_source_set_deinterlace_field_order';
function obs_source_get_deinterlace_field_order(ASource: POBSSource): TOBSDeinterlaceFieldOrder; cdecl; external 'obs.dll' name 'obs_source_get_deinterlace_field_order';
procedure obs_source_set_monitoring_type(ASource: POBSSource; ATyp: TOBSMonitoringType); cdecl; external 'obs.dll' name 'obs_source_set_monitoring_type';
function obs_source_get_monitoring_type(ASource: POBSSource): TOBSMonitoringType; cdecl; external 'obs.dll' name 'obs_source_get_monitoring_type';
function obs_source_get_private_settings(ASource: POBSSource): POBSData; cdecl; external 'obs.dll' name 'obs_source_get_private_settings';
function obs_source_get_type_data(ASource: POBSSource): Pointer; cdecl; external 'obs.dll' name 'obs_source_get_type_data';
procedure obs_source_draw_set_color_matrix(AColorMatrix: POBSMatrix4; AColorRangeMin, AColorRangeMax: POBSVec3); cdecl; external 'obs.dll' name 'obs_source_draw_set_color_matrix';
procedure obs_source_draw(AImage: POBSGSTexture; AX, AY: Integer; ACX, ACY: Cardinal; AFlip: Boolean); cdecl; external 'obs.dll' name 'obs_source_draw';
procedure obs_source_output_video(ASource: POBSSource; AFrame: POBSSourceFrame); cdecl; external 'obs.dll' name 'obs_source_output_video';
procedure obs_source_output_video2(ASource: POBSSource; AFrame: POBSSourceFrame2); cdecl; external 'obs.dll' name 'obs_source_output_video2';
procedure obs_source_set_async_rotation(ASource: POBSSource; ARotation: Longint); cdecl; external 'obs.dll' name 'obs_source_set_async_rotation';
procedure obs_source_output_cea708(ASource: POBSSource; ACaptions: POBSSourceCEA708); cdecl; external 'obs.dll' name 'obs_source_output_cea708';
procedure obs_source_preload_video(ASource: POBSSource; AFrame: POBSSourceFrame); cdecl; external 'obs.dll' name 'obs_source_preload_video';
procedure obs_source_preload_video2(ASource: POBSSource; AFrame: POBSSourceFrame2); cdecl; external 'obs.dll' name 'obs_source_preload_video2';
procedure obs_source_show_preloaded_video(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_show_preloaded_video';
procedure obs_source_set_video_frame(ASource: POBSSource; AFrame: POBSSourceFrame); cdecl; external 'obs.dll' name 'obs_source_set_video_frame';
procedure obs_source_set_video_frame2(ASource: POBSSource; AFrame: POBSSourceFrame2); cdecl; external 'obs.dll' name 'obs_source_set_video_frame2';
procedure obs_source_output_audio(ASource: POBSSource; AAudio: POBSSourceAudio); cdecl; external 'obs.dll' name 'obs_source_output_audio';
procedure obs_source_update_properties(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_update_properties';
function obs_source_get_frame(ASource: POBSSource): POBSSourceFrame; cdecl; external 'obs.dll' name 'obs_source_get_frame';
procedure obs_source_release_frame(ASource: POBSSource; AFrame: POBSSourceFrame); cdecl; external 'obs.dll' name 'obs_source_release_frame';
function obs_source_process_filter_begin(ASource: POBSSource; AFormat: TOBSGSColorFormat; AAllowDirect: TOBSAllowDirectRender): Boolean; cdecl; external 'obs.dll' name 'obs_source_process_filter_begin';
function obs_source_process_filter_begin_with_color_space(ASource: POBSSource; AFormat: TOBSGSColorFormat; ASpace: TOBSGSColorSpace; AAllowDirect: TOBSAllowDirectRender): Boolean; cdecl; external 'obs.dll' name 'obs_source_process_filter_begin_with_color_space';
procedure obs_source_process_filter_end(ASource: POBSSource; AEffect: POBSGSEffect; AWidth, AHeight: Cardinal); cdecl; external 'obs.dll' name 'obs_source_process_filter_end';
procedure obs_source_process_filter_tech_end(ASource: POBSSource; AEffect: POBSGSEffect; AWidth, AHeight: Cardinal; ATechName: PAnsiChar); cdecl; external 'obs.dll' name 'obs_source_process_filter_tech_end';
procedure obs_source_skip_video_filter(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_skip_video_filter';
function obs_source_add_active_child(AParent, AChild: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_add_active_child';
procedure obs_source_remove_active_child(AParent, AChild: POBSSource); cdecl; external 'obs.dll' name 'obs_source_remove_active_child';
procedure obs_source_send_mouse_click(ASource: POBSSource; AEvent: POBSMouseEvent; AType: Int32; AMouseUp: Boolean; AClickCount: Cardinal); cdecl; external 'obs.dll' name 'obs_source_send_mouse_click';
procedure obs_source_send_mouse_move(ASource: POBSSource; AEvent: POBSMouseEvent; AMouseLeave: Boolean); cdecl; external 'obs.dll' name 'obs_source_send_mouse_move';
procedure obs_source_send_mouse_wheel(ASource: POBSSource; AEvent: POBSMouseEvent; AXDelta: Integer; AYDelta: Integer); cdecl; external 'obs.dll' name 'obs_source_send_mouse_wheel';
procedure obs_source_send_focus(ASource: POBSSource; AFocus: Boolean); cdecl; external 'obs.dll' name 'obs_source_send_focus';
procedure obs_source_send_key_click(ASource: POBSSource; AEvent: POBSKeyEvent; AKeyUp: Boolean); cdecl; external 'obs.dll' name 'obs_source_send_key_click';
procedure obs_source_set_default_flags(ASource: POBSSource; AFlags: Cardinal); cdecl; external 'obs.dll' name 'obs_source_set_default_flags';
function obs_source_get_base_width(ASource: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_source_get_base_width';
function obs_source_get_base_height(ASource: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_source_get_base_height';
function obs_source_audio_pending(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_audio_pending';
function obs_source_get_audio_timestamp(ASource: POBSSource): UInt64; cdecl; external 'obs.dll' name 'obs_source_get_audio_timestamp';
procedure obs_source_get_audio_mix(ASource: POBSSource; AAudio: POBSSourceAudioMix); cdecl; external 'obs.dll' name 'obs_source_get_audio_mix';
procedure obs_source_set_async_unbuffered(ASource: POBSSource; AUnbuffered: Boolean); cdecl; external 'obs.dll' name 'obs_source_set_async_unbuffered';
function obs_source_async_unbuffered(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_async_unbuffered';
procedure obs_source_set_async_decoupled(ASource: POBSSource; ADecouple: Boolean); cdecl; external 'obs.dll' name 'obs_source_set_async_decoupled';
function obs_source_async_decoupled(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_async_decoupled';
procedure obs_source_set_audio_active(ASource: POBSSource; AShow: Boolean); cdecl; external 'obs.dll' name 'obs_source_set_audio_active';
function obs_source_audio_active(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_audio_active';
function obs_source_get_last_obs_version(ASource: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_source_get_last_obs_version';
procedure obs_source_media_play_pause(ASource: POBSSource; APause: Boolean); cdecl; external 'obs.dll' name 'obs_source_media_play_pause';
procedure obs_source_media_restart(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_media_restart';
procedure obs_source_media_stop(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_media_stop';
procedure obs_source_media_next(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_media_next';
procedure obs_source_media_previous(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_media_previous';
function obs_source_media_get_duration(ASource: POBSSource): Int64; cdecl; external 'obs.dll' name 'obs_source_media_get_duration';
function obs_source_media_get_time(ASource: POBSSource): Int64; cdecl; external 'obs.dll' name 'obs_source_media_get_time';
procedure obs_source_media_set_time(ASource: POBSSource; AMs: Int64); cdecl; external 'obs.dll' name 'obs_source_media_set_time';
function obs_source_media_get_state(ASource: POBSSource): TOBSMediaState; cdecl; external 'obs.dll' name 'obs_source_media_get_state';
procedure obs_source_media_started(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_media_started';
procedure obs_source_media_ended(ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_source_media_ended';
procedure obs_source_frame_init(AFrame: POBSSourceFrame; AFormat: TOBSVideoFormat; AWidth, AHeight: Cardinal); cdecl; external 'obs.dll' name 'obs_source_frame_init';
procedure obs_source_frame_copy(ADst, ASrc: POBSSourceFrame); cdecl; external 'obs.dll' name 'obs_source_frame_copy';
function obs_source_get_icon_type(AId: PAnsiChar): TOBSIconType; cdecl; external 'obs.dll' name 'obs_source_get_icon_type';
function obs_source_get_canvas(ASource: POBSSource): POBSCanvas; cdecl; external 'obs.dll' name 'obs_source_get_canvas';

function obs_transition_get_source(ATransition: POBSSource; ATarget: TOBSTransitionTarget): POBSSource; cdecl; external 'obs.dll' name 'obs_transition_get_source';
procedure obs_transition_clear(ATransition: POBSSource); cdecl; external 'obs.dll' name 'obs_transition_clear';
function obs_transition_get_active_source(ATransition: POBSSource): POBSSource; cdecl; external 'obs.dll' name 'obs_transition_get_active_source';
function obs_transition_start(ATransition: POBSSource; AMode: TOBSTransitionMode; ADurationMs: Cardinal; ADest: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_transition_start';
procedure obs_transition_set(ATransition: POBSSource; ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_transition_set';
procedure obs_transition_set_manual_time(ATransition: POBSSource; AT: Single); cdecl; external 'obs.dll' name 'obs_transition_set_manual_time';
procedure obs_transition_set_manual_torque(ATransition: POBSSource; ATorque, AClamp: Single); cdecl; external 'obs.dll' name 'obs_transition_set_manual_torque';
procedure obs_transition_set_scale_type(ATransition: POBSSource; ATyp: TOBSTransitionScaleType); cdecl; external 'obs.dll' name 'obs_transition_set_scale_type';
function obs_transition_get_scale_type(ATransition: POBSSource): TOBSTransitionScaleType; cdecl; external 'obs.dll' name 'obs_transition_get_scale_type';
procedure obs_transition_set_alignment(ATransition: POBSSource; AAlignment: Cardinal); cdecl; external 'obs.dll' name 'obs_transition_set_alignment';
function obs_transition_get_alignment(ATransition: POBSSource): Cardinal; cdecl; external 'obs.dll' name 'obs_transition_get_alignment';
procedure obs_transition_set_size(ATransition: POBSSource; ACX, ACY: Cardinal); cdecl; external 'obs.dll' name 'obs_transition_set_size';
procedure obs_transition_get_size(ATransition: POBSSource; ACX, ACY: PCardinal); cdecl; external 'obs.dll' name 'obs_transition_get_size';
function obs_transition_is_active(ATransition: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_transition_is_active';
procedure obs_transition_enable_fixed(ATransition: POBSSource; AEnable: Boolean; ADurationMs: Cardinal); cdecl; external 'obs.dll' name 'obs_transition_enable_fixed';
function obs_transition_fixed(ATransition: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_transition_fixed';
function obs_transition_get_time(ATransition: POBSSource): Single; cdecl; external 'obs.dll' name 'obs_transition_get_time';
procedure obs_transition_force_stop(ATransition: POBSSource); cdecl; external 'obs.dll' name 'obs_transition_force_stop';
procedure obs_transition_video_render(ATransition: POBSSource; ACallback: TOBSTransitionVideoRenderCallback); cdecl; external 'obs.dll' name 'obs_transition_video_render';
procedure obs_transition_video_render2(ATransition: POBSSource; ACallback: TOBSTransitionVideoRenderCallback; APlaceholderTexture: POBSGSTexture); cdecl; external 'obs.dll' name 'obs_transition_video_render2';
function obs_transition_video_get_color_space(ATransition: POBSSource): TOBSGSColorSpace; cdecl; external 'obs.dll' name 'obs_transition_video_get_color_space';
function obs_transition_video_render_direct(ATransition: POBSSource; ATarget: TOBSTransitionTarget): Boolean; cdecl; external 'obs.dll' name 'obs_transition_video_render_direct';
function obs_transition_audio_render(ATransition: POBSSource; ATimestampOut: PUInt64; AAudio: POBSSourceAudioMix; AMixers: Cardinal; AChannels, ASampleRate: NativeUInt; AMixACallback, AMixBCallback: TOBSTransitionAudioMixCallback): Boolean; cdecl; external 'obs.dll' name 'obs_transition_audio_render';
procedure obs_transition_swap_begin(ATransitionDest, ATransitionSource: POBSSource); cdecl; external 'obs.dll' name 'obs_transition_swap_begin';
procedure obs_transition_swap_end(ATransitionDest, ATransitionSource: POBSSource); cdecl; external 'obs.dll' name 'obs_transition_swap_end';

function obs_scene_create(AName: PAnsiChar): POBSScene; cdecl; external 'obs.dll' name 'obs_scene_create';
function obs_scene_create_private(AName: PAnsiChar): POBSScene; cdecl; external 'obs.dll' name 'obs_scene_create_private';
function obs_scene_duplicate(AScene: POBSScene; AName: PAnsiChar; ATyp: TOBSSceneDuplicateType): POBSScene; cdecl; external 'obs.dll' name 'obs_scene_duplicate';
procedure obs_scene_release(AScene: POBSScene); cdecl; external 'obs.dll' name 'obs_scene_release';
function obs_scene_get_ref(AScene: POBSScene): POBSScene; cdecl; external 'obs.dll' name 'obs_scene_get_ref';
function obs_scene_get_source(AScene: POBSScene): POBSSource; cdecl; external 'obs.dll' name 'obs_scene_get_source';
function obs_scene_from_source(ASource: POBSSource): POBSScene; cdecl; external 'obs.dll' name 'obs_scene_from_source';
function obs_scene_find_source(AScene: POBSScene; AName: PAnsiChar): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_find_source';
function obs_scene_find_source_recursive(AScene: POBSScene; AName: PAnsiChar): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_find_source_recursive';
function obs_scene_find_sceneitem_by_id(AScene: POBSScene; AId: Int64): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_find_sceneitem_by_id';
procedure obs_scene_enum_items(AScene: POBSScene; ACallback: TOBSSceneEnumItemsCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_scene_enum_items';
function obs_scene_reorder_items(AScene: POBSScene; AItemOrder: PPOBSSceneItem; AItemOrderSize: NativeUInt): Boolean; cdecl; external 'obs.dll' name 'obs_scene_reorder_items';
function obs_scene_reorder_items2(AScene: POBSScene; AItemOrder: POBSSceneItemOrderInfo; AItemOrderSize: NativeUInt): Boolean; cdecl; external 'obs.dll' name 'obs_scene_reorder_items2';
function obs_source_is_scene(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_is_scene';
function obs_source_type_is_scene(AId: PAnsiChar): Boolean; cdecl; external 'obs.dll' name 'obs_source_type_is_scene';
function obs_scene_add(AScene: POBSScene; ASource: POBSSource): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_add';
procedure obs_scene_atomic_update(AScene: POBSScene; AFunc: TOBSSceneAtomicUpdateFunc; AData: Pointer); cdecl; external 'obs.dll' name 'obs_scene_atomic_update';
procedure obs_sceneitem_addref(AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_addref';
procedure obs_sceneitem_release(AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_release';
procedure obs_sceneitem_remove(AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_remove';
procedure obs_sceneitems_add(AScene: POBSScene; AData: POBSDataArray); cdecl; external 'obs.dll' name 'obs_sceneitems_add';
procedure obs_sceneitem_save(AItem: POBSSceneItem; AData: POBSDataArray); cdecl; external 'obs.dll' name 'obs_sceneitem_save';
procedure obs_sceneitem_set_id(AItem: POBSSceneItem; AId: Int64); cdecl; external 'obs.dll' name 'obs_sceneitem_set_id';
function obs_scene_save_transform_states(AScene: POBSScene; AAllItems: Boolean): POBSData; cdecl; external 'obs.dll' name 'obs_scene_save_transform_states';
procedure obs_scene_load_transform_states(AState: PAnsiChar); cdecl; external 'obs.dll' name 'obs_scene_load_transform_states';
function obs_sceneitem_get_order_position(AItem: POBSSceneItem): Integer; cdecl; external 'obs.dll' name 'obs_sceneitem_get_order_position';
function obs_sceneitem_get_scene(AItem: POBSSceneItem): POBSScene; cdecl; external 'obs.dll' name 'obs_sceneitem_get_scene';
function obs_sceneitem_get_source(AItem: POBSSceneItem): POBSSource; cdecl; external 'obs.dll' name 'obs_sceneitem_get_source';
procedure obs_sceneitem_select(AItem: POBSSceneItem; ASelect: Boolean); cdecl; external 'obs.dll' name 'obs_sceneitem_select';
function obs_sceneitem_selected(AItem: POBSSceneItem): Boolean; cdecl; external 'obs.dll' name 'obs_sceneitem_selected';
function obs_sceneitem_locked(AItem: POBSSceneItem): Boolean; cdecl; external 'obs.dll' name 'obs_sceneitem_locked';
function obs_sceneitem_set_locked(AItem: POBSSceneItem; ALock: Boolean): Boolean; cdecl; external 'obs.dll' name 'obs_sceneitem_set_locked';
procedure obs_sceneitem_set_pos(AItem: POBSSceneItem; APos: POBSVec2); cdecl; external 'obs.dll' name 'obs_sceneitem_set_pos';
procedure obs_sceneitem_set_rot(AItem: POBSSceneItem; ARotDeg: Single); cdecl; external 'obs.dll' name 'obs_sceneitem_set_rot';
procedure obs_sceneitem_set_scale(AItem: POBSSceneItem; AScale: POBSVec2); cdecl; external 'obs.dll' name 'obs_sceneitem_set_scale';
procedure obs_sceneitem_set_alignment(AItem: POBSSceneItem; AAlignment: Cardinal); cdecl; external 'obs.dll' name 'obs_sceneitem_set_alignment';
procedure obs_sceneitem_set_order(AItem: POBSSceneItem; AMovement: TOBSOrderMovement); cdecl; external 'obs.dll' name 'obs_sceneitem_set_order';
procedure obs_sceneitem_set_order_position(AItem: POBSSceneItem; APosition: Integer); cdecl; external 'obs.dll' name 'obs_sceneitem_set_order_position';
procedure obs_sceneitem_set_bounds_type(AItem: POBSSceneItem; ATyp: TOBSBoundsType); cdecl; external 'obs.dll' name 'obs_sceneitem_set_bounds_type';
procedure obs_sceneitem_set_bounds_alignment(AItem: POBSSceneItem; AAlignment: Cardinal); cdecl; external 'obs.dll' name 'obs_sceneitem_set_bounds_alignment';
procedure obs_sceneitem_set_bounds_crop(AItem: POBSSceneItem; ACrop: Boolean); cdecl; external 'obs.dll' name 'obs_sceneitem_set_bounds_crop';
procedure obs_sceneitem_set_bounds(AItem: POBSSceneItem; ABounds: POBSVec2); cdecl; external 'obs.dll' name 'obs_sceneitem_set_bounds';
function obs_sceneitem_get_id(AItem: POBSSceneItem): Int64; cdecl; external 'obs.dll' name 'obs_sceneitem_get_id';
procedure obs_sceneitem_get_pos(AItem: POBSSceneItem; APos: POBSVec2); cdecl; external 'obs.dll' name 'obs_sceneitem_get_pos';
function obs_sceneitem_get_rot(AItem: POBSSceneItem): Single; cdecl; external 'obs.dll' name 'obs_sceneitem_get_rot';
procedure obs_sceneitem_get_scale(AItem: POBSSceneItem; AScale: POBSVec2); cdecl; external 'obs.dll' name 'obs_sceneitem_get_scale';
function obs_sceneitem_get_alignment(AItem: POBSSceneItem): Cardinal; cdecl; external 'obs.dll' name 'obs_sceneitem_get_alignment';
function obs_sceneitem_get_bounds_type(AItem: POBSSceneItem): TOBSBoundsType; cdecl; external 'obs.dll' name 'obs_sceneitem_get_bounds_type';
function obs_sceneitem_get_bounds_alignment(AItem: POBSSceneItem): Cardinal; cdecl; external 'obs.dll' name 'obs_sceneitem_get_bounds_alignment';
function obs_sceneitem_get_bounds_crop(AItem: POBSSceneItem): Boolean; cdecl; external 'obs.dll' name 'obs_sceneitem_get_bounds_crop';
procedure obs_sceneitem_get_bounds(AItem: POBSSceneItem; ABounds: POBSVec2); cdecl; external 'obs.dll' name 'obs_sceneitem_get_bounds';
procedure obs_sceneitem_get_info2(AItem: POBSSceneItem; AInfo: POBSTransformInfo); cdecl; external 'obs.dll' name 'obs_sceneitem_get_info2';
procedure obs_sceneitem_set_info2(AItem: POBSSceneItem; AInfo: POBSTransformInfo); cdecl; external 'obs.dll' name 'obs_sceneitem_set_info2';
procedure obs_sceneitem_get_draw_transform(AItem: POBSSceneItem; ATransform: POBSMatrix4); cdecl; external 'obs.dll' name 'obs_sceneitem_get_draw_transform';
procedure obs_sceneitem_get_box_transform(AItem: POBSSceneItem; ATransform: POBSMatrix4); cdecl; external 'obs.dll' name 'obs_sceneitem_get_box_transform';
procedure obs_sceneitem_get_box_scale(AItem: POBSSceneItem; AScale: POBSVec2); cdecl; external 'obs.dll' name 'obs_sceneitem_get_box_scale';
function obs_sceneitem_visible(AItem: POBSSceneItem): Boolean; cdecl; external 'obs.dll' name 'obs_sceneitem_visible';
function obs_sceneitem_set_visible(AItem: POBSSceneItem; AVisible: Boolean): Boolean; cdecl; external 'obs.dll' name 'obs_sceneitem_set_visible';
procedure obs_sceneitem_set_crop(AItem: POBSSceneItem; ACrop: POBSSceneItemCrop); cdecl; external 'obs.dll' name 'obs_sceneitem_set_crop';
procedure obs_sceneitem_get_crop(AItem: POBSSceneItem; ACrop: POBSSceneItemCrop); cdecl; external 'obs.dll' name 'obs_sceneitem_get_crop';
procedure obs_sceneitem_set_scale_filter(AItem: POBSSceneItem; AFilter: TOBSScaleType); cdecl; external 'obs.dll' name 'obs_sceneitem_set_scale_filter';
function obs_sceneitem_get_scale_filter(AItem: POBSSceneItem): TOBSScaleType; cdecl; external 'obs.dll' name 'obs_sceneitem_get_scale_filter';
procedure obs_sceneitem_set_blending_method(AItem: POBSSceneItem; AMethod: TOBSBlendingMethod); cdecl; external 'obs.dll' name 'obs_sceneitem_set_blending_method';
function obs_sceneitem_get_blending_method(AItem: POBSSceneItem): TOBSBlendingMethod; cdecl; external 'obs.dll' name 'obs_sceneitem_get_blending_method';
procedure obs_sceneitem_set_blending_mode(AItem: POBSSceneItem; ATyp: TOBSBlendingType); cdecl; external 'obs.dll' name 'obs_sceneitem_set_blending_mode';
function obs_sceneitem_get_blending_mode(AItem: POBSSceneItem): TOBSBlendingType; cdecl; external 'obs.dll' name 'obs_sceneitem_get_blending_mode';
procedure obs_sceneitem_force_update_transform(AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_force_update_transform';
procedure obs_sceneitem_defer_update_begin(AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_defer_update_begin';
procedure obs_sceneitem_defer_update_end(AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_defer_update_end';
function obs_sceneitem_get_private_settings(AItem: POBSSceneItem): POBSData; cdecl; external 'obs.dll' name 'obs_sceneitem_get_private_settings';
function obs_scene_add_group(AScene: POBSScene; AName: PAnsiChar): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_add_group';
function obs_scene_insert_group(AScene: POBSScene; AName: PAnsiChar; AItems: PPOBSSceneItem; ACount: NativeUInt): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_insert_group';
function obs_scene_add_group2(AScene: POBSScene; AName: PAnsiChar; ASignal: Boolean): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_add_group2';
function obs_scene_insert_group2(AScene: POBSScene; AName: PAnsiChar; AItems: PPOBSSceneItem; ACount: NativeUInt; ASignal: Boolean): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_insert_group2';
function obs_scene_get_group(AScene: POBSScene; AName: PAnsiChar): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_scene_get_group';
function obs_sceneitem_is_group(AItem: POBSSceneItem): Boolean; cdecl; external 'obs.dll' name 'obs_sceneitem_is_group';
function obs_sceneitem_group_get_scene(AGroup: POBSSceneItem): POBSScene; cdecl; external 'obs.dll' name 'obs_sceneitem_group_get_scene';
procedure obs_sceneitem_group_ungroup(AGroup: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_group_ungroup';
procedure obs_sceneitem_group_ungroup2(AGroup: POBSSceneItem; ASignal: Boolean); cdecl; external 'obs.dll' name 'obs_sceneitem_group_ungroup2';
procedure obs_sceneitem_group_add_item(AGroup, AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_group_add_item';
procedure obs_sceneitem_group_remove_item(AGroup, AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_group_remove_item';
function obs_sceneitem_get_group(AScene: POBSScene; AItem: POBSSceneItem): POBSSceneItem; cdecl; external 'obs.dll' name 'obs_sceneitem_get_group';
function obs_source_is_group(ASource: POBSSource): Boolean; cdecl; external 'obs.dll' name 'obs_source_is_group';
function obs_source_type_is_group(AId: PAnsiChar): Boolean; cdecl; external 'obs.dll' name 'obs_source_type_is_group';
function obs_scene_is_group(AScene: POBSScene): Boolean; cdecl; external 'obs.dll' name 'obs_scene_is_group';
procedure obs_sceneitem_group_enum_items(AGroup: POBSSceneItem; ACallback: TOBSSceneEnumItemsCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_sceneitem_group_enum_items';
function obs_group_from_source(ASource: POBSSource): POBSScene; cdecl; external 'obs.dll' name 'obs_group_from_source';
procedure obs_sceneitem_defer_group_resize_begin(AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_defer_group_resize_begin';
procedure obs_sceneitem_defer_group_resize_end(AItem: POBSSceneItem); cdecl; external 'obs.dll' name 'obs_sceneitem_defer_group_resize_end';
procedure obs_sceneitem_set_transition(AItem: POBSSceneItem; AShow: Boolean; ATransition: POBSSource); cdecl; external 'obs.dll' name 'obs_sceneitem_set_transition';
function obs_sceneitem_get_transition(AItem: POBSSceneItem; AShow: Boolean): POBSSource; cdecl; external 'obs.dll' name 'obs_sceneitem_get_transition';
procedure obs_sceneitem_set_transition_duration(AItem: POBSSceneItem; AShow: Boolean; ADurationMs: Cardinal); cdecl; external 'obs.dll' name 'obs_sceneitem_set_transition_duration';
function obs_sceneitem_get_transition_duration(AItem: POBSSceneItem; AShow: Boolean): Cardinal; cdecl; external 'obs.dll' name 'obs_sceneitem_get_transition_duration';
procedure obs_sceneitem_do_transition(AItem: POBSSceneItem; AVisible: Boolean); cdecl; external 'obs.dll' name 'obs_sceneitem_do_transition';
procedure obs_sceneitem_transition_load(AItem: POBSSceneItem; AData: POBSData; AShow: Boolean); cdecl; external 'obs.dll' name 'obs_sceneitem_transition_load';
function obs_sceneitem_transition_save(AItem: POBSSceneItem; AShow: Boolean): POBSData; cdecl; external 'obs.dll' name 'obs_sceneitem_transition_save';
procedure obs_scene_prune_sources(AScene: POBSScene); cdecl; external 'obs.dll' name 'obs_scene_prune_sources';

function obs_get_main_canvas: POBSCanvas; cdecl; external 'obs.dll' name 'obs_get_main_canvas';
function obs_canvas_create(AName: PAnsiChar; AVideoInfo: POBSVideoInfo; AFlags: Cardinal): POBSCanvas; cdecl; external 'obs.dll' name 'obs_canvas_create';
function obs_canvas_create_private(AName: PAnsiChar; AVideoInfo: POBSVideoInfo; AFlags: Cardinal): POBSCanvas; cdecl; external 'obs.dll' name 'obs_canvas_create_private';
procedure obs_canvas_remove(ACanvas: POBSCanvas); cdecl; external 'obs.dll' name 'obs_canvas_remove';
function obs_canvas_removed(ACanvas: POBSCanvas): Boolean; cdecl; external 'obs.dll' name 'obs_canvas_removed';
procedure obs_canvas_set_name(ACanvas: POBSCanvas; AName: PAnsiChar); cdecl; external 'obs.dll' name 'obs_canvas_set_name';
function obs_canvas_get_name(ACanvas: POBSCanvas): PAnsiChar; cdecl; external 'obs.dll' name 'obs_canvas_get_name';
function obs_canvas_get_uuid(ACanvas: POBSCanvas): PAnsiChar; cdecl; external 'obs.dll' name 'obs_canvas_get_uuid';
function obs_canvas_get_flags(ACanvas: POBSCanvas): Cardinal; cdecl; external 'obs.dll' name 'obs_canvas_get_flags';
function obs_save_canvas(ACanvas: POBSCanvas): POBSData; cdecl; external 'obs.dll' name 'obs_save_canvas';
function obs_load_canvas(AData: POBSData): POBSCanvas; cdecl; external 'obs.dll' name 'obs_load_canvas';
function obs_canvas_get_ref(ACanvas: POBSCanvas): POBSCanvas; cdecl; external 'obs.dll' name 'obs_canvas_get_ref';
procedure obs_canvas_release(ACanvas: POBSCanvas); cdecl; external 'obs.dll' name 'obs_canvas_release';
procedure obs_weak_canvas_addref(AWeak: POBSWeakCanvas); cdecl; external 'obs.dll' name 'obs_weak_canvas_addref';
procedure obs_weak_canvas_release(AWeak: POBSWeakCanvas); cdecl; external 'obs.dll' name 'obs_weak_canvas_release';
function obs_canvas_get_weak_canvas(ACanvas: POBSCanvas): POBSWeakCanvas; cdecl; external 'obs.dll' name 'obs_canvas_get_weak_canvas';
function obs_weak_canvas_get_canvas(AWeak: POBSWeakCanvas): POBSCanvas; cdecl; external 'obs.dll' name 'obs_weak_canvas_get_canvas';
function obs_canvas_get_signal_handler(ACanvas: POBSCanvas): POBSSignalHandler; cdecl; external 'obs.dll' name 'obs_canvas_get_signal_handler';
procedure obs_canvas_set_channel(ACanvas: POBSCanvas; AChannel: Cardinal; ASource: POBSSource); cdecl; external 'obs.dll' name 'obs_canvas_set_channel';
function obs_canvas_get_channel(ACanvas: POBSCanvas; AChannel: Cardinal): POBSSource; cdecl; external 'obs.dll' name 'obs_canvas_get_channel';
function obs_canvas_scene_create(ACanvas: POBSCanvas; AName: PAnsiChar): POBSScene; cdecl; external 'obs.dll' name 'obs_canvas_scene_create';
procedure obs_canvas_scene_remove(AScene: POBSScene); cdecl; external 'obs.dll' name 'obs_canvas_scene_remove';
procedure obs_canvas_move_scene(AScene: POBSScene; ADst: POBSCanvas); cdecl; external 'obs.dll' name 'obs_canvas_move_scene';
procedure obs_canvas_enum_scenes(ACanvas: POBSCanvas; AEnumProc: TOBSEnumSourcesCallback; AParam: Pointer); cdecl; external 'obs.dll' name 'obs_canvas_enum_scenes';
function obs_canvas_get_source_by_name(ACanvas: POBSCanvas; AName: PAnsiChar): POBSSource; cdecl; external 'obs.dll' name 'obs_canvas_get_source_by_name';
function obs_canvas_get_scene_by_name(ACanvas: POBSCanvas; AName: PAnsiChar): POBSScene; cdecl; external 'obs.dll' name 'obs_canvas_get_scene_by_name';
function obs_canvas_reset_video(ACanvas: POBSCanvas; AVideoInfo: POBSVideoInfo): Boolean; cdecl; external 'obs.dll' name 'obs_canvas_reset_video';
function obs_canvas_has_video(ACanvas: POBSCanvas): Boolean; cdecl; external 'obs.dll' name 'obs_canvas_has_video';
function obs_canvas_get_video(ACanvas: POBSCanvas): POBSVideoOutput; cdecl; external 'obs.dll' name 'obs_canvas_get_video';
function obs_canvas_get_video_info(ACanvas: POBSCanvas; AVideoInfo: POBSVideoInfo): Boolean; cdecl; external 'obs.dll' name 'obs_canvas_get_video_info';
procedure obs_canvas_render(ACanvas: POBSCanvas); cdecl; external 'obs.dll' name 'obs_canvas_render';

implementation

procedure obs_register_source(AInfo: POBSSourceInfo);
begin
  obs_register_source_s(AInfo, SizeOf(TOBSSourceInfo));
end;

end.
